### ISSUE TITLE
Green Fang Kobolds

### ISSUE THREAD

**Issue by phildhub** [angry-monsters/angry-monsters.github.io#2]
[green fang kobold warrior.txt](https://github.com/angry-monsters/angry-monsters.github.io/files/5168115/green.fang.kobold.warrior.txt)
[green fang kobold sting spitter.txt](https://github.com/angry-monsters/angry-monsters.github.io/files/5168200/green.fang.kobold.sting.spitter.txt)
[green fang winged kobold.txt](https://github.com/angry-monsters/angry-monsters.github.io/files/5168117/green.fang.winged.kobold.txt)
[green fang kobold snaketamer.txt](https://github.com/angry-monsters/angry-monsters.github.io/files/5168203/green.fang.kobold.snaketamer.txt)
[trained constrictor snake.txt](https://github.com/angry-monsters/angry-monsters.github.io/files/5168288/trained.constrictor.snake.txt)

This is a set of apprentice tier kobolds designed to be used together in encounter building.
The kobolds are poison themed, having resistance to poison damage and some of them dealing it themselves.

The green fang kobold warrior is a basic melee warrior kobold
The green fang sting spitter is a basic ranged attacker that spits poison darts
The green fang winged kobold is a flyer that can drop poison powder bombs that deal aoe poison damage, as well as normal rocks.
The kobold snaketamer is a controller type kobold designed to be used in encounters in combination with the trained constrictor snake. His bonus action ability allows him to direct his pet constrictor snake to move as a reaction, which opens up interesting battlefield control opportunities once the constrictor has grappled a PC.

**Comment by hokieboat** [comment]
Awesome, thanks!!
