### ISSUE TITLE
GM and Player versions of the Companion stat block

### ISSUE THREAD

**Issue by kalidrev** [angry-monsters/angry-monsters.github.io#4]
In Angry's article, it describes having one version of the Companion for the GM and another version for the Player. Currently, the Interaction section (dimension?) is not selectable in the dropdown for hiding dimensions.

I would like to be able to hide and unhide the Interaction section so that I can print out (or save a picture of) a GM version or a Player version of the Companion.

Without this, I cannot create a Player version of the Companion, as even without adding anything to the Interaction section/loyalty features, the "Interaction" heading still appears.

**Comment by hokieboat** [comment]
Fixed! That feature was there...then I accidentally deleted it during a previous update, so thank you for bringing it to my attention.
